// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmgtMkfeFo_P1xgREw-FweqtyTV_F1pwk',
    appId: '1:669903803430:web:e063f4954fdd4ec1e682e7',
    messagingSenderId: '669903803430',
    projectId: 'arfit-5a52f',
    authDomain: 'arfit-5a52f.firebaseapp.com',
    storageBucket: 'arfit-5a52f.appspot.com',
    measurementId: 'G-TWM80KZXBE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsEmupYc7rfj_LdirHUxtr1bPw0aEb0eg',
    appId: '1:669903803430:android:3bcd35d3e34658abe682e7',
    messagingSenderId: '669903803430',
    projectId: 'arfit-5a52f',
    storageBucket: 'arfit-5a52f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC7hE6ie4Y829qdwIbynSQNp45GKgf1zE',
    appId: '1:669903803430:ios:5a6a736abe262e06e682e7',
    messagingSenderId: '669903803430',
    projectId: 'arfit-5a52f',
    storageBucket: 'arfit-5a52f.appspot.com',
    iosClientId: '669903803430-hbsskoefdk2qhl52qi1thkhc7e69ob5m.apps.googleusercontent.com',
    iosBundleId: 'com.example.arfit',
  );
}
